site_name: 吉大一生物信息学实验室
site_description: '生信实验室/平台'
site_author: 'sandy'
site_url: 'https://guan-biolab.github.io'
theme:
  name: 'material'
  palette:
    scheme: default
    primary: 'indigo'
  features:
    - navigation.tabs
    - navigation.sections
  #custom_dir: sources #overrides
#copyright: 'Copyright &copy; 2016 - 2021 HZCDC@Lab'
repo_url: https://github.com/Guan-biolab/guan-biolab.github.io

extra:
  palette:
    primary: 'blue'

extra_css:
  - assets/stylesheets/extra.css

nav:
  - 'Home': index.md
  - 'People': people.md
    - '工作人员':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md
    - '博士生':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md      
    - '硕士生':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md 
  - 'Publications': publications.md
  - 'News': news.md
    - '最近更新':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md
    - '队伍壮大':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md      
    - '团建活动':
      - '01. XX': book/1.Raw_Data/01_database.md
      - '02. XX': book/1.Raw_Data/02_get-data.md
      - '03. XX': book/1.Raw_Data/03_entrez.md  

  - 'Noot':
  
    - '第一章 常用工具':
      - '01. 基因组公共数据库': book/1.Raw_Data/01_database.md
      - '02. 下载基因组数据': book/1.Raw_Data/02_get-data.md
      - '03. Entrez 工具': book/1.Raw_Data/03_entrez.md
      - '04. Blast 比对': book/1.Raw_Data/04_blast.md
      - '06. FastQC': book/1.Raw_Data/05_fastqc.md
      - '06. Multiqc': book/1.Raw_Data/06_multiqc.md
      - '07. SeqKit 工具': book/1.Raw_Data/07_seqkit.md
      - '08. Trimmomatic 工具': book/1.Raw_Data/08_trimmomatic.md
    - '第二章 组装与比对':
      - '01. 基本比对流程': book/2.To_Genome/01_bwa-samtools-pipeline.md
      - '02. 细菌基因组组装': book/2.To_Genome/02_bacteria-assembly.md
    - '第三章 基因组注释':
      - '01. Prokka 快速注释': book/3.Genome_Annotation/01_prokka.md
      - '02. Eggnog 注释': book/3.Genome_Annotation/02_eggnog.md
      - '03. SNP注释工具 snpEFF': book/3.Genome_Annotation/03_snpeff.md

    - '第四章 基因组比较':
      - '01. mummer': book/4.Genome_Compare/01_mummer.md
      - '02. mauve': book/4.Genome_Compare/02_mauve.md

use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.emoji:
   #   emoji_index: !!python/name:material.extensions.emoji.twemoji
    #  emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  #        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.progressbar

#google_analytics: ['UA-55420348-3', 'auto']

plugins:
  - search
 # - git-authors
 # - git-revision-date
 # - macros