site_name: 吉大一生物信息学实验室
site_description: '生信实验室/平台'
site_author: 'sandy'
site_url: 'https://guan-biolab.github.io'
theme:
  name: 'material'
  palette:
    scheme: default
    primary: 'indigo'
  features:
    - navigation.tabs
    - navigation.sections
  #custom_dir: sources #overrides
#copyright: 'Copyright &copy; 2016 - 2021 HZCDC@Lab'
repo_url: https://github.com/Guan-biolab/guan-biolab.github.io

extra:
  palette:
    primary: 'blue'

extra_css:
  - assets/stylesheets/extra.css

nav:
  - '首页': main.md
  - '数据分析笔记':
  
    - '第二章 组装与比对':
      - '01. 基本比对流程': book/C02_Raw-Data-to-Genome/01_bwa-samtools-pipeline.md
      - '02. Quast 验证': book/C02_Raw-Data-to-Genome/02_quast.md
      - '03. 细菌基因组组装': book/C02_Raw-Data-to-Genome/03_bacteria-assembly.md
      - '04. 病毒基因组组装': book/C02_Raw-Data-to-Genome/04_virus-assembly.md
      - '05. GATK3': book/C02_Raw-Data-to-Genome/05_gatk3.md
      - '06. GATK4': book/C02_Raw-Data-to-Genome/06_gatk4.md
use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - attr_list
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.emoji:
   #   emoji_index: !!python/name:material.extensions.emoji.twemoji
    #  emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  #        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.progressbar

#google_analytics: ['UA-55420348-3', 'auto']

plugins:
  - search
 # - git-authors
 # - git-revision-date
 # - macros